/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculator;

/**
 *
 * @author KUMAR ADITYA
 */
public class CalculatorApplication extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorApplication
     */
     double firstnumber;
    double secondnumber;
    double result;
    String operator;
    
    public CalculatorApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Result = new javax.swing.JTextField();
        Equall = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        Mod = new javax.swing.JButton();
        Dot = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Sub = new javax.swing.JButton();
        Div = new javax.swing.JButton();
        Mul = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Result.setBorder(null);
        Result.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultActionPerformed(evt);
            }
        });
        getContentPane().add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 220, 40));

        Equall.setText("=");
        Equall.setBorder(null);
        Equall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquallActionPerformed(evt);
            }
        });
        getContentPane().add(Equall, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 100, 30));

        num1.setText("1");
        num1.setBorder(null);
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        getContentPane().add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 40, 30));

        num2.setText("2");
        num2.setBorder(null);
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        getContentPane().add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 40, 30));

        num3.setText("3");
        num3.setBorder(null);
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        getContentPane().add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 40, 30));

        num4.setText("4");
        num4.setBorder(null);
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        getContentPane().add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 40, 30));

        num5.setText("5");
        num5.setBorder(null);
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        getContentPane().add(num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 40, 30));

        num6.setText("6");
        num6.setBorder(null);
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });
        getContentPane().add(num6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 40, 30));

        num7.setText("7");
        num7.setBorder(null);
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });
        getContentPane().add(num7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 40, 30));

        num8.setText("8");
        num8.setBorder(null);
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        getContentPane().add(num8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 40, 30));

        num9.setText("9");
        num9.setBorder(null);
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        getContentPane().add(num9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 40, 30));

        Mod.setText("%");
        Mod.setBorder(null);
        Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModActionPerformed(evt);
            }
        });
        getContentPane().add(Mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 40, 30));

        Dot.setText(".");
        Dot.setBorder(null);
        Dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DotActionPerformed(evt);
            }
        });
        getContentPane().add(Dot, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 40, 30));

        Clear.setText("C");
        Clear.setBorder(null);
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 100, 30));

        num0.setText("0");
        num0.setBorder(null);
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        getContentPane().add(num0, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 40, 30));

        Add.setText("+");
        Add.setBorder(null);
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 40, 30));

        Sub.setText("-");
        Sub.setBorder(null);
        Sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubActionPerformed(evt);
            }
        });
        getContentPane().add(Sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 40, 30));

        Div.setText("/");
        Div.setBorder(null);
        Div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivActionPerformed(evt);
            }
        });
        getContentPane().add(Div, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 40, 30));

        Mul.setText("*");
        Mul.setBorder(null);
        Mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MulActionPerformed(evt);
            }
        });
        getContentPane().add(Mul, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 40, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultActionPerformed

    private void EquallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquallActionPerformed
        // TODO add your handling code here:
        secondnumber = Double.parseDouble(Result.getText());
        if(operator == "+")
        {result=firstnumber+secondnumber;
            Result.setText(Double.toString(result));}
        else if(operator == "-")
        {result=firstnumber-secondnumber;
           Result.setText(Double.toString(result));}
         else if(operator == "/")
        {result=firstnumber/secondnumber;
            Result.setText(Double.toString(result));}
         else if(operator == "*")
        {result=firstnumber*secondnumber;
            Result.setText(Double.toString(result));}
         else if(operator == "%")
             {result=firstnumber%secondnumber;
            Result.setText(Double.toString(result));}
    }//GEN-LAST:event_EquallActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
        String number = Result.getText()+ num1.getText();
        Result.setText(number);
        
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
        String number = Result.getText()+ num2.getText();
        Result.setText(number);
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        // TODO add your handling code here:
        String number = Result.getText()+ num3.getText();
        Result.setText(number);
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        // TODO add your handling code here:
        String number = Result.getText()+ num4.getText();
        Result.setText(number);
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        // TODO add your handling code here:
        String number = Result.getText()+ num5.getText();
        Result.setText(number);
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        // TODO add your handling code here:
        String number = Result.getText()+ num6.getText();
        Result.setText(number);
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        // TODO add your handling code here:
        String number = Result.getText()+ num7.getText();
        Result.setText(number);
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        // TODO add your handling code here:
        String number = Result.getText()+ num8.getText();
        Result.setText(number);
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        // TODO add your handling code here:
        String number = Result.getText()+ num9.getText();
        Result.setText(number);
    }//GEN-LAST:event_num9ActionPerformed

    private void ModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModActionPerformed
        // TODO add your handling code here:
        firstnumber = Double.parseDouble(Result.getText());
      Result.setText(" ");
operator="%";  
    }//GEN-LAST:event_ModActionPerformed

    private void DotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DotActionPerformed
        // TODO add your handling code here:
        String number = Result.getText()+ Dot.getText();
        Result.setText(number);
    }//GEN-LAST:event_DotActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        Result.setText(" ");
    }//GEN-LAST:event_ClearActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        // TODO add your handling code here:
        String number = Result.getText()+ num0.getText();
        Result.setText(number);
    }//GEN-LAST:event_num0ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
       firstnumber = Double.parseDouble(Result.getText());
      Result.setText(" ");
operator="+";
    }//GEN-LAST:event_AddActionPerformed

    private void SubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubActionPerformed
        // TODO add your handling code here:
        firstnumber = Double.parseDouble(Result.getText());
      Result.setText(" ");
operator="-";  
    }//GEN-LAST:event_SubActionPerformed

    private void DivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivActionPerformed
        // TODO add your handling code here:
       firstnumber = Double.parseDouble(Result.getText());
      Result.setText(" ");
operator="/";  
    }//GEN-LAST:event_DivActionPerformed

    private void MulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MulActionPerformed
        // TODO add your handling code here:
       firstnumber = Double.parseDouble(Result.getText());
      Result.setText(" ");
operator="*";    
    }//GEN-LAST:event_MulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Div;
    private javax.swing.JButton Dot;
    private javax.swing.JButton Equall;
    private javax.swing.JButton Mod;
    private javax.swing.JButton Mul;
    private javax.swing.JTextField Result;
    private javax.swing.JButton Sub;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    // End of variables declaration//GEN-END:variables
}
